name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the 'main' branch
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version here

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # This is the branch where the built project will be deployed
          folder: dist      # The directory to deploy from (usually dist for Vite)
