name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment (use Node.js 20.x for Vite compatibility)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build command
      - name: Build the project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev  # Ensure gh-pages is installed
          npm run deploy  # This will push the dist folder to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
